#!/bin/bash

set -euo pipefail

root_dir="$(cd "$(dirname "$0")/../.." && pwd -P)"
source_dir="$root_dir/design/app-store/ios-real-screens"
output_dir="$root_dir/design/app-store/ios-upload-draft-screens"
force=0

usage() {
  cat <<'USAGE'
Usage: scripts/ios/export-app-store-screenshot-draft.sh [options]

Exports the current Nome iOS 10-slot App Store planning set as flattened JPEGs.
This is a draft package, not a final upload package: files that still depend on
preview core or debug preview evidence are named with "needs-real-core".

Options:
  --source DIR   Source candidate directory. Default: design/app-store/ios-real-screens
  --output DIR   Output draft directory. Default: design/app-store/ios-upload-draft-screens
  --force        Replace an existing non-empty output directory.
  -h, --help     Show this help.
USAGE
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --source)
      shift
      if [ "$#" -eq 0 ]; then
        echo "[FAIL] --source requires a directory" >&2
        exit 2
      fi
      source_dir="$1"
      ;;
    --output)
      shift
      if [ "$#" -eq 0 ]; then
        echo "[FAIL] --output requires a directory" >&2
        exit 2
      fi
      output_dir="$1"
      ;;
    --force)
      force=1
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "[FAIL] Unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
  shift
done

cd "$root_dir"

if ! command -v sips >/dev/null 2>&1; then
  echo "[FAIL] sips is required on macOS" >&2
  exit 2
fi

if ! command -v shasum >/dev/null 2>&1; then
  echo "[FAIL] shasum is required" >&2
  exit 2
fi

if [ ! -d "$source_dir" ]; then
  echo "[FAIL] Source screenshot directory does not exist: $source_dir" >&2
  exit 2
fi

if [ -d "$output_dir" ] && [ "$(find "$output_dir" -mindepth 1 -maxdepth 1 | wc -l | tr -d '[:space:]')" -gt 0 ]; then
  if [ "$force" -ne 1 ]; then
    echo "[FAIL] Output directory is not empty: $output_dir" >&2
    echo "[INFO] Re-run with --force to replace generated draft files." >&2
    exit 1
  fi
  find "$output_dir" -mindepth 1 -maxdepth 1 -type f \( -name '*.jpg' -o -name '*.jpeg' -o -name '*.png' -o -name 'MANIFEST.md' -o -name 'README.md' -o -name 'FINAL_BLOCKERS.md' \) -delete
fi

mkdir -p "$output_dir"

items=(
  "01-onboarding-welcome.png|01-onboarding-welcome.jpg|ready|Onboarding welcome. Re-capture from final build if copy changes.|No real-core blocker; recapture only if final copy or build styling changes."
  "02-onboarding-local-identity.png|02-onboarding-local-identity.jpg|ready|Local identity onboarding. Re-capture from final build if copy changes.|No real-core blocker; recapture only if final copy or build styling changes."
  "03-home.png|03-home.jpg|ready|Nome home screen.|No real-core blocker; recapture only if final home UI changes."
  "04-contacts.png|04-contacts.jpg|ready|Contacts tab visual candidate.|No real-core blocker; recapture only if final contacts UI changes."
  "11-add-friend-preview-core.png|05-add-friend-needs-real-core.jpg|needs-real-core|Replace with a real one-time link and QR screenshot.|Real iOS core creates a one-time invitation link and QR code without preview placeholders."
  "05-public-contact-preview-core.png|06-public-contact-needs-real-core.jpg|needs-real-core|Replace with a real public contact address screenshot.|Real profile has a public contact address visible and copy/share actions available."
  "06-join-group-preview.png|07-join-group-needs-real-core.jpg|needs-real-core|Replace after real group invitation preview or join test.|Real group invite link opens a preview or join path against the real core."
  "07-conversation-debug-preview.png|08-conversation-needs-real-core.jpg|needs-real-core|Replace with a real two-account conversation screenshot.|Two-account real conversation shows sent and received messages from the real core."
  "08-settings.png|09-settings.jpg|ready|Settings tab visual candidate.|No real-core blocker; recapture only if final settings UI changes."
  "10-help.png|10-help.jpg|ready|Help and feedback visual candidate.|No real-core blocker; recapture only if final help UI changes."
)

manifest="$output_dir/MANIFEST.md"
readme="$output_dir/README.md"
blockers="$output_dir/FINAL_BLOCKERS.md"

cat > "$manifest" <<'HEADER'
# Nome iOS App Store screenshot draft export

This directory is generated by:

```bash
scripts/ios/export-app-store-screenshot-draft.sh --force
```

It is a 10-slot flattened JPEG export for planning. Treat it as final only when
every row status is `ready` and the strict screenshot check passes.

| Slot | Export file | Source file | Dimensions | Bytes | SHA-256 | Status | Final-release note |
| --- | --- | --- | --- | --- | --- | --- | --- |
HEADER

cat > "$readme" <<'HEADER'
# Nome iOS App Store screenshot draft

This directory contains a generated 10-slot JPEG planning package. It removes
the eleventh candidate and flattens alpha channels, but it still marks
preview-core/debug-derived screens as `needs-real-core`.

Use this check for the draft:

```bash
scripts/ios/check-app-store-screenshots.sh --dir design/app-store/ios-upload-draft-screens
```

Strict final mode must continue to fail until the `needs-real-core` files are
replaced and `MANIFEST.md` / `FINAL_BLOCKERS.md` no longer record
preview/debug/needs-real-core status:

```bash
scripts/ios/check-app-store-screenshots.sh --final --dir design/app-store/ios-upload-draft-screens
```
HEADER

cat > "$blockers" <<'HEADER'
# Nome iOS App Store final blockers

This file is generated by:

```bash
scripts/ios/export-app-store-screenshot-draft.sh --force
```

The current screenshot draft is not a final App Store Connect upload package
while this file lists any screenshot rows below.

| Slot | Draft file | Source candidate | Status | Replacement evidence required |
| --- | --- | --- | --- | --- |
HEADER

slot=0
needs_real_core=0

for item in "${items[@]}"; do
  IFS='|' read -r source_name output_name status note evidence <<< "$item"
  source_path="$source_dir/$source_name"
  output_path="$output_dir/$output_name"

  slot=$((slot + 1))

  if [ ! -f "$source_path" ]; then
    echo "[FAIL] Missing source screenshot: $source_path" >&2
    exit 1
  fi

  sips -s format jpeg -s formatOptions 95 "$source_path" --out "$output_path" >/dev/null

  width="$(sips -g pixelWidth "$output_path" 2>/dev/null | awk '/pixelWidth/{print $2}')"
  height="$(sips -g pixelHeight "$output_path" 2>/dev/null | awk '/pixelHeight/{print $2}')"
  bytes="$(wc -c < "$output_path" | tr -d '[:space:]')"
  sha="$(shasum -a 256 "$output_path" | awk '{print $1}')"

  if [ "$status" = "needs-real-core" ]; then
    needs_real_core=$((needs_real_core + 1))
    printf '| %s | `%s` | `%s` | `%s` | %s |\n' \
      "$slot" "$output_name" "$source_name" "$status" "$evidence" >> "$blockers"
  fi

  printf '| %s | `%s` | `%s` | `%sx%s` | `%s` | `%s` | `%s` | %s |\n' \
    "$slot" "$output_name" "$source_name" "$width" "$height" "$bytes" "$sha" "$status" "$note" >> "$manifest"

  printf '[OK] %02d %s <- %s (%s)\n' "$slot" "$output_name" "$source_name" "$status"
done

if [ "$needs_real_core" -eq 0 ]; then
  printf '\nNo final screenshot blockers are recorded for this generated package.\n' >> "$blockers"
else
  cat <<EOF >> "$blockers"

Current blocker count: $needs_real_core

Final mode must keep failing until these screenshots are replaced, filenames no
longer contain \`needs-real-core\`, and the manifest status for each replacement
is updated from \`needs-real-core\` to \`ready\`.
EOF
fi

cat <<EOF

[PASS] Draft screenshot export completed
[INFO] Output: $output_dir
[INFO] Slots: $slot
[INFO] Needs real-core replacement: $needs_real_core
[INFO] Manifest: $manifest
[INFO] Final blockers: $blockers

Next checks:
  scripts/ios/check-app-store-screenshots.sh --dir "$output_dir"
  scripts/ios/check-app-store-screenshots.sh --final --dir "$output_dir"
EOF
