package chat.simplex.common.ui.nome.tokens

import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.Color

@Immutable
class NomeColorTokens internal constructor(
  val isDark: Boolean,
  val brandNavy: Color,
  val brandGreen: Color,
  val action: Color,
  val onAction: Color,
  val accent: Color,
  val onAccent: Color,
  val background: Color,
  val surface: Color,
  val surfaceSubtle: Color,
  val surfaceContainer: Color,
  val surfaceRaised: Color,
  val input: Color,
  val border: Color,
  val divider: Color,
  val textPrimary: Color,
  val textSecondary: Color,
  val textTertiary: Color,
  val textInverse: Color,
  val info: Color,
  val infoContainer: Color,
  val onInfoContainer: Color,
  val success: Color,
  val successContainer: Color,
  val onSuccessContainer: Color,
  val warning: Color,
  val warningContainer: Color,
  val onWarningContainer: Color,
  val danger: Color,
  val onDanger: Color,
  val dangerContainer: Color,
  val onDangerContainer: Color,
  val disabledContainer: Color,
  val disabledContent: Color,
  val scrim: Color,
  val sentMessage: Color,
  val sentMessageBorder: Color,
  val receivedMessage: Color,
  val receivedMessageBorder: Color,
)

internal val NomeLightColorTokens = NomeColorTokens(
  isDark = false,
  brandNavy = Color(0xFF0E1B2D),
  brandGreen = Color(0xFF16AE66),
  action = Color(0xFF0A874D),
  onAction = Color.White,
  accent = Color(0xFF276BFF),
  onAccent = Color.White,
  background = Color.White,
  surface = Color.White,
  surfaceSubtle = Color(0xFFF5F7FA),
  surfaceContainer = Color(0xFFF8FAFC),
  surfaceRaised = Color.White,
  input = Color.White,
  border = Color(0xFFD0D5DD),
  divider = Color(0xFFEAECF0),
  textPrimary = Color(0xFF0E1B2D),
  textSecondary = Color(0xFF667085),
  textTertiary = Color(0xFF68717F),
  textInverse = Color.White,
  info = Color(0xFF276BFF),
  infoContainer = Color(0xFFEFF4FF),
  onInfoContainer = Color(0xFF1D56CC),
  success = Color(0xFF0A874D),
  successContainer = Color(0xFFECFDF3),
  onSuccessContainer = Color(0xFF067647),
  warning = Color(0xFFB54708),
  warningContainer = Color(0xFFFFFAEB),
  onWarningContainer = Color(0xFFB54708),
  danger = Color(0xFFB42318),
  onDanger = Color.White,
  dangerContainer = Color(0xFFFEF3F2),
  onDangerContainer = Color(0xFFB42318),
  disabledContainer = Color(0xFFE4E7EC),
  disabledContent = Color(0xFF667085),
  scrim = Color(0x990E1B2D),
  sentMessage = Color(0xFFEAF8F0),
  sentMessageBorder = Color(0xFFB7E7CC),
  receivedMessage = Color(0xFFF5F7FA),
  receivedMessageBorder = Color(0xFFD0D5DD),
)

internal val NomeDarkColorTokens = NomeColorTokens(
  isDark = true,
  brandNavy = Color(0xFF0E1B2D),
  brandGreen = Color(0xFF16AE66),
  action = Color(0xFF0A874D),
  onAction = Color.White,
  accent = Color(0xFF276BFF),
  onAccent = Color.White,
  background = Color(0xFF0E1B2D),
  surface = Color(0xFF121F32),
  surfaceSubtle = Color(0xFF121F32),
  surfaceContainer = Color(0xFF17273C),
  surfaceRaised = Color(0xFF1D3048),
  input = Color(0xFF1A2B41),
  border = Color(0xFF30445C),
  divider = Color(0xFF30445C),
  textPrimary = Color(0xFFF7F9FC),
  textSecondary = Color(0xFFB5C0CF),
  textTertiary = Color(0xFF8E9AAC),
  textInverse = Color(0xFF0E1B2D),
  info = Color(0xFF79A5FF),
  infoContainer = Color(0xFF172A4A),
  onInfoContainer = Color(0xFF79A5FF),
  success = Color(0xFF71DC9F),
  successContainer = Color(0xFF123626),
  onSuccessContainer = Color(0xFF71DC9F),
  warning = Color(0xFFF2B26B),
  warningContainer = Color(0xFF2F2418),
  onWarningContainer = Color(0xFFF2B26B),
  danger = Color(0xFFFF8D85),
  onDanger = Color(0xFF0E1B2D),
  dangerContainer = Color(0xFF321F22),
  onDangerContainer = Color(0xFFFF8D85),
  disabledContainer = Color(0xFF25364C),
  disabledContent = Color(0xFF8E9AAC),
  scrim = Color(0xB3000000),
  sentMessage = Color(0xFF143D2D),
  sentMessageBorder = Color(0xFF245B40),
  receivedMessage = Color(0xFF17273C),
  receivedMessageBorder = Color(0xFF30445C),
)
